// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

namespace Server.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20190206221550_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Server.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("text_id");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnName("text_content");

                    b.HasKey("Id");

                    b.HasAlternateKey("TextContent")
                        .HasName("AlternateKey_TextContent");

                    b.ToTable("text");
                });
#pragma warning restore 612, 618
        }
    }
}
